apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: todo-frontend
  name: todo-frontend
  namespace: todo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-frontend

  template:
    metadata:
      labels:
        app: todo-frontend

    spec:
      serviceAccountName: todo-frontend-sa

      containers:
      - name: http-echo
        image: hashicorp/http-echo
        imagePullPolicy: Always

        command:
        - /http-echo
        - -text=Todo Frontend OK

        ports:
        - containerPort: 5678

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
