server {
  listen 3000;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  location /api/ {
    proxy_pass http://platform-gateway-istio.istio-system.svc.cluster.local:8080/;
    proxy_http_version 1.1;
    proxy_set_header Host api.todo.local;
    proxy_set_header X-Request-Id $http_x_request_id;
    proxy_set_header X-B3-TraceId $http_x_b3_traceid;
    proxy_set_header X-B3-SpanId $http_x_b3_spanid;
    proxy_set_header X-B3-ParentSpanId $http_x_b3_parentspanid;
    proxy_set_header X-B3-Sampled $http_x_b3_sampled;
    proxy_set_header X-B3-Flags $http_x_b3_flags;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
