apiVersion: v1
kind: Service

metadata:
  labels:
    app: todo-frontend
  name: todo-frontend
  namespace: todo

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

  selector:
    app: todo-frontend

  type: ClusterIP
