apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: todo-api
  name: todo-api
  namespace: todo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-api

  template:
    metadata:
      labels:
        app: todo-api

    spec:
      containers:
      - name: todo-api

        image: 192.168.1.50:30926/todo-api:v2

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: DB_HOST
          value: postgres

        - name: DB_USER
          value: todo

        - name: DB_PASSWORD
          value: todo123

        - name: DB_NAME
          value: todo

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080

        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080

        resources:
          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi
