apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: todo-api
  name: todo-api
  namespace: todo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-api

  template:
    metadata:
      labels:
        app: todo-api

    spec:
      containers:
      - name: http-echo
        image: 192.168.1.50:30926/registry-demo:v1
        imagePullPolicy: Always
        command:
        - /http-echo
        - -text=Todo API OK
