apiVersion: v1
kind: Service

metadata:
  labels:
    app: todo-api
  name: todo-api
  namespace: todo

spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678

  selector:
    app: todo-api

  type: ClusterIP
