apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-config
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "5" }
spec:
  project: default
  source: { repoURL: https://github.com/jusefe11/linktic, targetRevision: main, path: gitops/manifests/observability }
  destination: { server: https://kubernetes.default.svc, namespace: istio-system }
  syncPolicy: { automated: { prune: false, selfHeal: true } }
