apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - certificates.yaml
  - metallb.yaml
  - registry.yaml
  - database.yaml
  - gateway.yaml
  - routes.yaml
  - todo-security.yaml
  - public-tunnel.yaml
