apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: todo-tracing
  namespace: todo
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: todo-metrics
  namespace: todo
spec:
  metrics:
    - providers:
        - name: prometheus
